
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcoqoijwpmqkzqvwkhhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjb3FvaWp3cG1xa3pxdndraGhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwOTU4NjYsImV4cCI6MjA1ODY3MTg2Nn0.ANxVLNJ6N_goNKMbpJBgZCfWWarQEeVYrp_gRADUThk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: localStorage
  }
});

// Make sure only admin user can access the admin panel
export const isAdmin = async () => {
  const { data } = await supabase.auth.getSession();
  return data.session?.user.email === 'mateuszniema1@gmail.com';
};
